"""The only module in Continuum permitted filesystem access (ADR-0001 Layer 3).

Enforced by the import-linter contract in ``.importlinter``: no other package
may import ``os``, ``pathlib``, ``shutil``, ``tempfile``, ``zipfile`` or call
bare ``open()`` for filesystem work.
"""

from continuum_storage.acquisition import (
    ACQUISITION_DOCUMENTS,
    AcquisitionCliError,
    AcquisitionDocument,
    AcquisitionStore,
    CliResult,
    VaultChanges,
)
from continuum_storage.derived import DerivedStore, StoredArtifact
from continuum_storage.media import (
    MEDIA_ID_PATTERN,
    ArchiveListing,
    ArchivePage,
    MediaFile,
    MediaLibrary,
    MediaUnavailableError,
    RecordSupplement,
    engine_index_records,
    media_id_for,
)
from continuum_storage.paths import (
    RESERVED_DEVICE_NAMES,
    ResolvedPath,
    resolve_within,
    same_file_as,
    validate_relative_candidate,
)
from continuum_storage.probe import (
    ReadOnlyStatus,
    SyncFolderWarning,
    VaultProtectionReport,
    detect_sync_provider,
    probe_vault_readonly,
)
from continuum_storage.projects import (
    LIFECYCLE,
    MANIFEST_NAME,
    PROJECT_ID_PATTERN,
    Project,
    ProjectDocument,
    ProjectLibrary,
)
from continuum_storage.reports import StoredReport, read_report, write_report
from continuum_storage.roots import (
    RootStatus,
    StorageEnvironment,
    build_storage,
    validate_roots,
)
from continuum_storage.sources import (
    HeldUnit,
    SourceAccess,
    SourceChangedError,
    SourceUnavailableError,
    UnitBytes,
    normalized_entry,
)
from continuum_storage.survey import (
    ArchiveInspection,
    ArchiveMemberInfo,
    ArchivePageGroup,
    CatalogRoot,
    FileChangedError,
    FileProbe,
    SurveyedFile,
    SurveyReadError,
    SurveySkip,
    VaultSurvey,
    catalog_roots,
    hash_catalog_file,
    inspect_archive,
    probe_file,
    stat_file,
    survey_root,
)
from continuum_storage.vault import SourceVaultReader, VaultEntry

__all__ = [
    "ACQUISITION_DOCUMENTS",
    "LIFECYCLE",
    "MANIFEST_NAME",
    "MEDIA_ID_PATTERN",
    "PROJECT_ID_PATTERN",
    "RESERVED_DEVICE_NAMES",
    "AcquisitionCliError",
    "AcquisitionDocument",
    "AcquisitionStore",
    "ArchiveInspection",
    "ArchiveListing",
    "ArchiveMemberInfo",
    "ArchivePage",
    "ArchivePageGroup",
    "CatalogRoot",
    "CliResult",
    "DerivedStore",
    "FileChangedError",
    "FileProbe",
    "HeldUnit",
    "MediaFile",
    "MediaLibrary",
    "MediaUnavailableError",
    "Project",
    "ProjectDocument",
    "ProjectLibrary",
    "ReadOnlyStatus",
    "RecordSupplement",
    "ResolvedPath",
    "RootStatus",
    "SourceAccess",
    "SourceChangedError",
    "SourceUnavailableError",
    "SourceVaultReader",
    "StorageEnvironment",
    "StoredArtifact",
    "StoredReport",
    "SurveyReadError",
    "SurveySkip",
    "SurveyedFile",
    "SyncFolderWarning",
    "UnitBytes",
    "VaultChanges",
    "VaultEntry",
    "VaultProtectionReport",
    "VaultSurvey",
    "build_storage",
    "catalog_roots",
    "detect_sync_provider",
    "engine_index_records",
    "hash_catalog_file",
    "inspect_archive",
    "media_id_for",
    "normalized_entry",
    "probe_file",
    "probe_vault_readonly",
    "read_report",
    "resolve_within",
    "same_file_as",
    "stat_file",
    "survey_root",
    "validate_relative_candidate",
    "validate_roots",
    "write_report",
]
